### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by Tjoosten** [benedmunds/PHP-Ion-Auth#15]
hi @benedmunds  can u add a chatroom from gitter. in this repo

**Comment by benedmunds** [comment]
Not sure its a good idea. Thoughts @kayla?

**Comment by Tjoosten** [comment]
I think maybe later we can provide support with that chatroom

**Comment by benedmunds** [comment]
I'd rather just use issues. If it blows up we could eventually move to IRC. But i hope we don't end up doing support daily even.

**Comment by Tjoosten** [comment]
Hmm ok srry. For the idea

**Comment by benedmunds** [comment]
Oh never be sorry for an idea! Thanks for bringing it up
